In [1]:
# Dependencies
import pandas as pd

In [2]:
# Import AFC file
afcpath = 'NFL_AFC.xls'

afc = pd.read_excel(afcpath)

In [3]:
# Create DataFrame
afc_df = pd.DataFrame(afc)
afc_df

,Tm,W,L,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS
0,New England Patriots*,10,6,0.625,427,285,142,8.9,2.3,11.2,6.7,4.5
1,New York Jets+,9,7,0.563,348,236,112,7.0,1.6,8.6,1.1,7.5
2,Miami Dolphins,7,9,0.438,360,390,-30,-1.9,3.6,1.7,2.9,-1.2
3,Buffalo Bills,6,10,0.375,258,326,-68,-4.3,2.4,-1.8,-4.5,2.7
4,Cincinnati Bengals*,10,6,0.625,305,291,14,0.9,-0.2,0.7,-2.5,3.2
5,Baltimore Ravens+,9,7,0.563,391,261,130,8.1,-0.7,7.5,2.6,4.9
6,Pittsburgh Steelers,9,7,0.563,368,324,44,2.8,-1.1,1.7,1.0,0.7
7,Cleveland Browns,5,11,0.313,245,375,-130,-8.1,-0.3,-8.4,-6.0,-2.4
8,Indianapolis Colts*,14,2,0.875,416,307,109,6.8,-0.9,5.9,4.4,1.5
9,Houston Texans,9,7,0.563,388,333,55,3.4,-1.5,2.0,2.7,-0.7
10,Tennessee Titans,8,8,0.500,354,402,-48,-3.0,0.2,-2.8,0.9,-3.6
11,Jacksonville Jaguars,7,9,0.438,290,380,-90,-5.6,-0.9,-6.5,-3.8,-2.6
12,San Diego Chargers*,13,3,0.813,454,320,134,8.4,-1.7,6.6,6.4,0.2
13,Denver Broncos,8,8,0.500,326,324,2,0.1,0.2,0.3,-1.0,1.3
14,Oakland Raiders,5,11,0.313,197,379,-182,-11.4,1.1,-10.3,-8.7,-1.6
15,Kansas City Chiefs,4,12,0.250,294,424,-130,-8.1,-0.3,-8.4,-2.5,-5.9

In [4]:
# Drop Unneeded Columns
afc_rec = afc_df[['Tm', 'W', 'L', 'W-L%']].copy()
afc_rec

                       Tm   W   L   W-L%
0   New England Patriots*  10   6  0.625
1          New York Jets+   9   7  0.563
2          Miami Dolphins   7   9  0.438
3           Buffalo Bills   6  10  0.375
4     Cincinnati Bengals*  10   6  0.625
5       Baltimore Ravens+   9   7  0.563
6     Pittsburgh Steelers   9   7  0.563
7        Cleveland Browns   5  11  0.313
8     Indianapolis Colts*  14   2  0.875
9          Houston Texans   9   7  0.563
10       Tennessee Titans   8   8  0.500
11   Jacksonville Jaguars   7   9  0.438
12    San Diego Chargers*  13   3  0.813
13         Denver Broncos   8   8  0.500
14        Oakland Raiders   5  11  0.313
15     Kansas City Chiefs   4  12  0.250

In [5]:
# Insert City Location
afc_cities = ['Boston', 'New York', 'Miami', 'Buffalo', 'Cincinnati', 'Baltimore', 'Pittsburgh', 'Cleveland', 'Indianapolis',
             'Houston', 'Nashville', 'Jacksonville', 'San Diego', 'Denver', 'Oakland', 'Kansas City']

afc_rec['City'] = afc_cities

In [6]:
# Rename Column to 'Team Name'
afc_rec = afc_rec.rename(columns={'Tm':'Team Name'})

In [7]:
# Verify Clean Data for AFC Record
afc_rec

                Team Name   W   L   W-L%          City
0   New England Patriots*  10   6  0.625        Boston
1          New York Jets+   9   7  0.563      New York
2          Miami Dolphins   7   9  0.438         Miami
3           Buffalo Bills   6  10  0.375       Buffalo
4     Cincinnati Bengals*  10   6  0.625    Cincinnati
5       Baltimore Ravens+   9   7  0.563     Baltimore
6     Pittsburgh Steelers   9   7  0.563    Pittsburgh
7        Cleveland Browns   5  11  0.313     Cleveland
8     Indianapolis Colts*  14   2  0.875  Indianapolis
9          Houston Texans   9   7  0.563       Houston
10       Tennessee Titans   8   8  0.500     Nashville
11   Jacksonville Jaguars   7   9  0.438  Jacksonville
12    San Diego Chargers*  13   3  0.813     San Diego
13         Denver Broncos   8   8  0.500        Denver
14        Oakland Raiders   5  11  0.313       Oakland
15     Kansas City Chiefs   4  12  0.250   Kansas City

In [8]:
# Import NFC file
nfcpath = 'NFL_NFC.xls'

nfc = pd.read_excel(nfcpath)

In [9]:
# Create DataFrame
nfc_df = pd.DataFrame(nfc)
nfc_df

,Tm,W,L,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS
0,Dallas Cowboys*,11,5,0.688,361,250,111,6.9,0.2,7.1,0.4,6.7
1,Philadelphia Eagles+,11,5,0.688,429,337,92,5.8,0.2,6.0,5.8,0.2
2,New York Giants,8,8,0.500,402,427,-25,-1.6,1.6,0.1,4.6,-4.5
3,Washington Redskins,4,12,0.250,266,336,-70,-4.4,-0.2,-4.6,-5.5,1.0
4,Minnesota Vikings*,12,4,0.750,470,312,158,9.9,-2.7,7.2,6.6,0.6
5,Green Bay Packers+,11,5,0.688,461,297,164,10.3,-2.9,7.4,6.3,1.1
6,Chicago Bears,7,9,0.438,327,375,-48,-3.0,-0.9,-3.9,-1.9,-2.0
7,Detroit Lions,2,14,0.125,262,494,-232,-14.5,0.1,-14.4,-5.2,-9.2
8,New Orleans Saints*,13,3,0.813,510,341,169,10.6,0.2,10.8,11.2,-0.5
9,Atlanta Falcons,9,7,0.563,363,325,38,2.4,2.7,5.0,2.7,2.3
10,Carolina Panthers,8,8,0.500,315,308,7,0.4,3.5,3.9,-0.6,4.5
11,Tampa Bay Buccaneers,3,13,0.188,244,400,-156,-9.8,4.1,-5.6,-4.6,-1.1
12,Arizona Cardinals*,10,6,0.625,375,325,50,3.1,-3.4,-0.3,0.1,-0.4
13,San Francisco 49ers,8,8,0.500,330,281,49,3.1,-3.0,0.1,-2.9,3.0
14,Seattle Seahawks,5,11,0.313,280,390,-110,-6.9,-2.4,-9.3,-5.0,-4.4
15,St. Louis Rams,1,15,0.063,175,436,-261,-16.3,-1.1,-17.4,-11.7,-5.8

In [10]:
# Drop Unneeded Columns
nfc_rec = nfc_df[['Tm', 'W', 'L', 'W-L%']].copy()
nfc_rec

                      Tm   W   L   W-L%
0        Dallas Cowboys*  11   5  0.688
1   Philadelphia Eagles+  11   5  0.688
2        New York Giants   8   8  0.500
3    Washington Redskins   4  12  0.250
4     Minnesota Vikings*  12   4  0.750
5     Green Bay Packers+  11   5  0.688
6          Chicago Bears   7   9  0.438
7          Detroit Lions   2  14  0.125
8    New Orleans Saints*  13   3  0.813
9        Atlanta Falcons   9   7  0.563
10     Carolina Panthers   8   8  0.500
11  Tampa Bay Buccaneers   3  13  0.188
12    Arizona Cardinals*  10   6  0.625
13   San Francisco 49ers   8   8  0.500
14      Seattle Seahawks   5  11  0.313
15        St. Louis Rams   1  15  0.063

In [ ]:
# Insert City Location
nfc_cities = ['Dallas', 'Philadelphia', 'New York', 'DC', 'Minneapolis', 'Green Bay', 'Chicago', 'Detroit', 'New Orleans',
              'Atlanta', 'Charlotte', 'Tampa Bay', 'Phoenix', 'San Francisco', 'Seattle', 'St. Louis']

nfc_rec['City'] = nfc_cities